### ISSUE TITLE
Wierd Protege 5.0 load issue with lastest versions of dcat.rdf and dcat.ttl - opens as inconsistent

### ISSUE THREAD

**Issue by rduerr** [w3c/dxwg#1100]
As an add on to #944, I opened both the latest version of dcat.ttl and dcat.rdf by URL from within Protege 5.5.0 Build beta-8.  In both cases, the ontologies loaded OK, but contained spurious Error1, Error2, and Error3 (only in the .rdf version) entities (see screen shot below).

Strangely enough, if I download the files from github and then open them in Protege, I get the very same errors!  However, if I remove the spurious subclass statements, save the file, then reopen it, the errors stay gone!  Since there are no obvious Error# axioms in the online files, this seems quite strange!  Not quite sure where the error is coming from.

<img width="1697" alt="Screen Shot 2019-09-26 at 3 09 19 PM" src="https://user-images.githubusercontent.com/1544892/65725370-b427a700-e06f-11e9-9253-ac6c41786a50.png">

**Comment by dr-shorthair** [comment]
This is almost certainly because two axioms that were added in ec746b24b333218771594bfffd49908fd0e5361a 
```
foaf:homepage a owl:ObjectProperty .
foaf:primaryTopic a owl:ObjectProperty .
```
were then moved into dcat-external.ttl in c7504d07b425054dc4c5452694c43c44b32b49df

I guess they should be moved back so that Protege users are not inconvenienced.

**Comment by davebrowning** [comment]
(Github auto-close reversed)

@rduerr - we believe we've addressed this - would appreciate confirmation that it works in your environment.

**Comment by rduerr** [comment]
Hmmm... the dcat.ttl file worked fine; but the dcat.rdf file still has the same problems.

**Comment by dr-shorthair** [comment]
Looks like I may have overlooked the need to regenerate the RDF version. Try this now: https://raw.githubusercontent.com/w3c/dxwg/dcat-issue1100/dcat/rdf/dcat.rdf

**Comment by rduerr** [comment]
Aargh!  Relationship is still showing up as error1; but the other two are gone.  So, it is better!  Close but no cigar.

**Comment by dr-shorthair** [comment]
But the dcat.ttl file loads fine? Protege can be a bit fierce about some OWL issues, but that should not depend on the serialization. 

The only thing that is special about the axiomatization of `dcat:Relationship` is a cardinality constraint on an outgoing `dct:relation`, without which the Relationship is incomplete. 

We are using the ttl version as the reference version. 
I converted to the other formats using TopBraid, which I think uses Jena under the hood.
We could try a different re-serializer, like http://rdfvalidator.mybluemix.net/, but if it is based on the same RDF library then the result will likely be the same.

**Comment by dr-shorthair** [comment]
I've regenerated the RDF and JSON-LD encodings using Protege instead of TopBraid.

**Comment by andrea-perego** [comment]
@rduerr , could you please confirm PR https://github.com/w3c/dxwg/pull/1142 fixes the issue?

**Comment by andrea-perego** [comment]
PR #1142 should have fixed the issue. If not, a new one should be created.

Closing.
