### ISSUE TITLE
Update Roles vocab and publish W3C styling

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#535]
The `ResourceRoles` vocabulary published formerly only as an RDF file (https://github.com/w3c/dxwg/blob/gh-pages/profilesont/resource_roles.ttl) and an image (https://github.com/w3c/dxwg/blob/gh-pages/profilesont/resource_roles.png). 

Following discussion with Dave Raggat, Ralph Swick and others within F2F4, it was suggested that the vocab be published as an auxiliary document in W3C styling now, before the W3C has established a dynamic vocabulary management system, and then perhaps to be updated later.

**Comment by nicholascar** [comment]
I have created an updated vocab document here: https://raw.githack.com/w3c/dxwg/profilesont-doc/profilesont/resource_roles.html and have created a PR to bring it, and updated RDF & img files, into the head gh-pages branch: https://github.com/w3c/dxwg/pull/532.

Currently no direct references (links) from the ontology document point to this vocabulary as it hasn't been 'live'. Such links will need to be added.

**Comment by aisaac** [comment]
Sorry but your reflection on F2F4 doesn't match my own position there, which I've mentioned at https://github.com/w3c/dxwg/issues/536#issuecomment-436414686
I believe that we should have all the default roles in the main vocabulary, just like the Web Annotation model and vocabulary do. I'm ok revisting this later, when/if W3C has something. For the moment I would go for the simpler option.

**Comment by kcoyle** [comment]
@aisaac Are you referring to the "[Named Individuals](https://www.w3.org/TR/annotation-vocab/#named-individuals)" in the web annotation ontology? That does look like a good model. 

Given how minimal the profiles ontology is, my gut feeling is that people will have a need to expand on it, adding some descriptive and administrative properties. (As it is, you don't even have metadata for whose proflie it is or for what purpose.) This could be done as a profile of the ontology but logically, as with DCAT, it would make sense eventually to incorporate common additions into the ontology itself. I'm not sure that the roles will be that much more volatile than the base ontology unless the assumption is that the ontology is only the basis for profiles that will be used by actual implementations.

**Comment by nicholascar** [comment]
I've just made a bunch of updates to the Roles vocab to cover off on a number of issues. If/when these changes are merged (there are a bunch of pending PRs) then I'll propose bringing them into the main ontology with a specific Issue for that (this Issue was originally about styling).

**Comment by aisaac** [comment]
@kcoyle yes I was precisely refering to these [named individuals](https://www.w3.org/TR/annotation-vocab/#named-individuals) that implement the [vocabulary for motivations in Web Annotations](https://www.w3.org/TR/annotation-model/#motivation-and-purpose). This vocabulary can be extended, but the concepts that have been defined by the WAWG are in the main spec.

**Comment by andrea-perego** [comment]
Copying my comment https://github.com/w3c/dxwg/issues/536#issuecomment-457943549 as per @aisaac request:

I wonder whether part of the discussion was about allowing people to add new roles in the future under the same role: namespace. If this is the case, I don't think this is actually a requirement and we shouldn't not go that way. New roles to be used in PROF can also be added under other / new namespaces.

**Comment by nicholascar** [comment]
The original issue of styling has been addressed so I'm marking for closure. Additional issues about roles' locations & namespaces exist to carry the remaining points forward.

**Comment by kcoyle** [comment]
"styling"? can you be more specific? Thanks.

**Comment by nicholascar** [comment]
@kcoyle just the HTML/CSS styling. This way just a Look 'n Feel issue and it's now addressed (and somewhat superseded due to Roles in the main doc) so I'm closing.

**Comment by kcoyle** [comment]
The group has not reviewed the change to the doc. Please do not close the issue until there is group approval.

**Comment by tombaker** [comment]
[Watching from the sidelines...]  This is confusing -  https://raw.githack.com/w3c/dxwg/profilesont-doc/profilesont/resource_roles.html does not resolve and it is unclear what documents are affected (and in what way).  

In principle, the resolution closing an issue should be fairly self-contained, with a clear statement of what the group resolved and with links to relevant documents, mailing list postings, minutes and/or, if applicable, to a Github diffs.  Otherwise, it is difficult for an interested outsider to follow what is happening without catching up on some very long threads.

Alot of this used to be handled automatically by W3C infrastructure - see the example issue https://www.w3.org/2006/07/SWD/track/issues/86 .  The old style admittedly sets a high bar, but some of this could be replicated with well-formulated resolutions.

**Comment by nicholascar** [comment]
Redundant as now in the one document.

**Comment by tombaker** [comment]
@nicholascar Can you please provide a link?

**Comment by kcoyle** [comment]
Here's a link to the Google doc where discussion was taking place: https://docs.google.com/document/d/1ddygq4EcKr1DzJykdhM_WxkkmTAoU1qQWsf8xuZxcKc/edit

That was prior to the publication, and there is no indication of resolution via consensus. 

This is why I have been insisting that the roles question is not resolved because I see this as not following the necessary consensus process - the editors made decisions without getting consensus from the discussants. So we still need consensus on 1) what roles will be included in the document as the "basic set" and 2) how they are defined. The fact that roles were included in the document does not mean that this issue is resolved.

**Comment by kcoyle** [comment]
@nicholascar I think that @tombaker is asking for the link to the "one document" that you mention. I also do not know what you are referring to. Thanks.

**Comment by nicholascar** [comment]
The "one document" I referred to is the PROF document itself: https://www.w3.org/TR/dx-prof/. [Section 8](https://www.w3.org/TR/dx-prof/#resource-roles-vocab) contains the starting point roles vocabulary.

**Comment by aisaac** [comment]
ok I think this fits what was required in the first comment. I still have some reservations about using a separate namespace for roles, but I'm going to raise this as a separate issue.

**Comment by kcoyle** [comment]
And I still have reservations about the roles that are included and their definitions, so I'll raise that as a separate issue.

**Comment by nicholascar** [comment]
Separate Issue raised at #1049

**Comment by aisaac** [comment]
I think this issue could now be closed.

**Comment by kcoyle** [comment]
Yes, as long as we agree that the question of which roles are in the document/exist is not weighted based on the fact that some were entered into the document for the 2pwd. I don't want that to be cited as a precedent because those roles were not agreed by consensus. So if the closure statement could state this I would agree.

**Comment by nicholascar** [comment]
No, there will be no assumption that the roles entered into the 2PWD are good/special/accepted. They were just a catalyst for discussion.

Closing after listing in plenary [2019-09-03](https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.09.03) + 3-day wait period.

**Comment by kcoyle** [comment]
@nicholascar it's best to say what the RESOLUTION of the issue is, not just that it was listed in an agenda. I believe that the RESOLUTION here is that there are still issues with roles, and that is being discussed at #1049.

**Comment by aisaac** [comment]
@kcoyle I believe that the discussion in March (starting from [this comment](https://github.com/w3c/dxwg/issues/535#issuecomment-469897015)) was decent enough for closing and then our new issue was visible enough. But as I've gone through the comments, I'll try a recap on behalf of @nicholascar and you:
- the original issue of styling has been addressed 
- additional issues about roles' locations & namespaces have been raised (and perhaps closed) to continue some of the older discussion points in this issue.
- a new issue for discussing the roles themselves has been created at #1049 
- it's been proposed for closing on the plenary agenda for one week and nobody brought new reasons for keeping it open

**Comment by nicholascar** [comment]
Thanks for the wrapping-up comment @aisaac. I've noted your style for future use!
